my_pollsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
	#modifying path conf for calling generic views.
	path('',views.IndexView.as_view(),name='index'),
	path('<int:pk>/',views.DetailView.as_view(), name='detail'),
	path('<int:pk>/result',views.ResultView.as_view(), name='result'),
	path('<int:question_id>/vote', views.vote, name='vote'),
]

polls/models.py
import datetime 

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField()

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.views import generic
from django.urls import reverse
from django.utils import timezone

# Create your views here.

#Implemnting Generic Views using "generic" as Superclass.
class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'list_of_questions'

	def get_queryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

	def get_queryset(self):
		"only question from the past"
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultView(generic.DetailView):
	model = Question
	template_name = 'polls/result.html'
'''
def index(request):
	list_of_questions = Question.objects.order_by('-pub_date')
	return render(request,'polls/index.html', {'list_of_questions': list_of_questions})

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request,'polls/detail.html', {'question': question})

def results(request, question_id):
	return HttpResponse(f"You are looking at result of question {question_id}")
'''
def vote(request, question_id):
	question = get_object_or_404(Question,pk=question_id)
	try:
		selected_choice = Choice.objects.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You did not select a choice"
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		
		# now we redirect insted of render(as if done so by clicking back button it will post the form again)
		# reverse generates url and takes view name and agruments if any
		return HttpResponseRedirect(reverse('polls:result', args=(question.id,)))
	

polls/templates/polls/detail.html
<h1>{{question.question_text}}</h1>
{% if error_message %}<p><strong>{{error_message}}</strong></p> {% endif %}	
<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
		{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
		<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br />
		{% endfor %}
	<input type="submit" value="Vote" />
</form>
	

polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>

{% if list_of_questions %}
	<ul>
	{% for question in list_of_questions %}
	<li><a href="{% url 'polls:detail' question.id%}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No Polls available</p>
{% endif %}

polls/templates/polls/result.html
<h1>{{question.question_text}}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>{{choice.choice_text}} -- {{choice.votes}} vote{{ choice.votes|pluralize }}</li>
	{% endfor %}
</ul>